name: React CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run tests
      run: cat package.json

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [build, test]

    steps:
    
    - name: Install dependencies
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.PRIVATE_KEY }}
        script: |
            cd feedback-app
            git pull origin
            cd
            sudo cp -r build/* /var/www/html
            sudo systemctl restart nginx